package com.itas.taxfiling.observability.filter;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import org.slf4j.MDC;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.info.BuildProperties;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

/**
 * Injects {@code component_version} into MDC for every HTTP request — manifesto §3
 * Coding & Logging Standards: "Every log entry must include the component_version
 * so errors can be isolated to a specific released version."
 * <p>
 * Version is resolved from {@code META-INF/build-info.properties} (generated by
 * {@code spring-boot-maven-plugin:build-info}). That file is only present in packaged
 * JARs / the built target dir — <b>not</b> when running via {@code mvn spring-boot:run}
 * or an IDE launcher. We therefore depend on {@link ObjectProvider} so the filter
 * still starts cleanly when the properties file is missing, falling back to "unknown".
 * <p>
 * Ordering: runs before {@code MdcContextFilter} so correlation/actor filters see
 * the version already in MDC — {@link Order} 0.
 */
@Component
@Order(0)
public class ComponentVersionMdcFilter extends OncePerRequestFilter {

    private static final String MDC_KEY = "component_version";
    private static final String FALLBACK = "unknown";

    private final String version;

    public ComponentVersionMdcFilter(ObjectProvider<BuildProperties> buildPropsProvider) {
        BuildProperties bp = buildPropsProvider.getIfAvailable();
        this.version = bp != null ? bp.getVersion() : FALLBACK;
    }

    @Override
    protected void doFilterInternal(HttpServletRequest req, HttpServletResponse resp, FilterChain chain)
            throws ServletException, IOException {
        MDC.put(MDC_KEY, version);
        try {
            chain.doFilter(req, resp);
        } finally {
            MDC.remove(MDC_KEY);
        }
    }
}
