-- Lazy-materialization migration for filing periods (Rule 5 follow-up).
-- See plan in CLAUDE.md / migration spec. Three changes:
--   1. New calendar_period table — cached global calendar projection from tax-type-engine.
--   2. derive_period_status() — stored function used in the dashboard JOIN query.
--   3. filing_period gains materialized_at; legacy unfiled rows are reclaimed.

-- ─── 1. calendar_period projection ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS calendar_period (
    id            UUID         PRIMARY KEY,
    tax_type_code VARCHAR(64)  NOT NULL,
    period_label  VARCHAR(32)  NOT NULL,
    starts_on     DATE         NOT NULL,
    ends_on       DATE         NOT NULL,
    due_on        DATE         NOT NULL,
    frequency     VARCHAR(16)  NOT NULL,
    source        VARCHAR(32)  NOT NULL DEFAULT 'TAX_TYPE_ENGINE',
    refreshed_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ux_calendar_period_type_label UNIQUE (tax_type_code, period_label)
);

CREATE INDEX IF NOT EXISTS ix_calendar_period_type_starts
    ON calendar_period (tax_type_code, starts_on);

CREATE INDEX IF NOT EXISTS ix_calendar_period_due
    ON calendar_period (due_on);

-- ─── 2. derive_period_status() ───────────────────────────────────────────────
-- Single source of truth for date-driven status. Used by the dashboard query
-- and by the Java side via FilingPeriod.statusFor (both must stay in sync).
CREATE OR REPLACE FUNCTION derive_period_status(
    p_starts_on  DATE,
    p_covers_to  DATE,
    p_due_on     DATE,
    p_today      DATE
) RETURNS VARCHAR(16)
LANGUAGE SQL IMMUTABLE AS $$
    SELECT CASE
        WHEN p_today <  p_starts_on THEN 'FUTURE'
        WHEN p_today >  p_due_on    THEN 'OVERDUE'
        WHEN p_today >  p_covers_to THEN 'DUE'
        ELSE 'OPEN'
    END;
$$;

-- ─── 3. filing_period.materialized_at ────────────────────────────────────────
ALTER TABLE filing_period
    ADD COLUMN IF NOT EXISTS materialized_at TIMESTAMPTZ;

UPDATE filing_period
    SET materialized_at = created_at
    WHERE materialized_at IS NULL;

-- ─── 4. Reclaim legacy eager rows ────────────────────────────────────────────
-- Anything pre-generated by GenerateInitialFilingPeriodsUseCase that never got
-- linked to a tax return is now redundant — status will be derived from the
-- calendar instead. Production rollout should batch this; for the demo DB it's
-- a one-shot.
DELETE FROM filing_period
    WHERE tax_return_id IS NULL
      AND status IN ('FUTURE', 'OPEN', 'DUE', 'OVERDUE');
