/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObligationsRouteImport } from './routes/obligations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemIndexRouteImport } from './routes/system.index'
import { Route as ReturnsIndexRouteImport } from './routes/returns.index'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as SystemValidationRouteImport } from './routes/system.validation'
import { Route as SystemOutboxRouteImport } from './routes/system.outbox'
import { Route as ReturnsNewRouteImport } from './routes/returns.new'
import { Route as ReturnsIdRouteImport } from './routes/returns.$id'
import { Route as OfficerQueueRouteImport } from './routes/officer.queue'
import { Route as OfficerHistoryRouteImport } from './routes/officer.history'
import { Route as ReturnsMonthlyIndexRouteImport } from './routes/returns.monthly.index'
import { Route as ReturnsDailyIndexRouteImport } from './routes/returns.daily.index'
import { Route as ReturnsMonthlyNewRouteImport } from './routes/returns.monthly.new'
import { Route as ReturnsMonthlyIdRouteImport } from './routes/returns.monthly.$id'
import { Route as ReturnsDailyNewRouteImport } from './routes/returns.daily.new'
import { Route as ReturnsDailyIdRouteImport } from './routes/returns.daily.$id'
import { Route as OfficerCaseIdRouteImport } from './routes/officer.case.$id'

const ObligationsRoute = ObligationsRouteImport.update({
  id: '/obligations',
  path: '/obligations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIndexRoute = ReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/officer/',
  path: '/officer/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemValidationRoute = SystemValidationRouteImport.update({
  id: '/system/validation',
  path: '/system/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemOutboxRoute = SystemOutboxRouteImport.update({
  id: '/system/outbox',
  path: '/system/outbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsNewRoute = ReturnsNewRouteImport.update({
  id: '/returns/new',
  path: '/returns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIdRoute = ReturnsIdRouteImport.update({
  id: '/returns/$id',
  path: '/returns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerQueueRoute = OfficerQueueRouteImport.update({
  id: '/officer/queue',
  path: '/officer/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerHistoryRoute = OfficerHistoryRouteImport.update({
  id: '/officer/history',
  path: '/officer/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsMonthlyIndexRoute = ReturnsMonthlyIndexRouteImport.update({
  id: '/returns/monthly/',
  path: '/returns/monthly/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsDailyIndexRoute = ReturnsDailyIndexRouteImport.update({
  id: '/returns/daily/',
  path: '/returns/daily/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsMonthlyNewRoute = ReturnsMonthlyNewRouteImport.update({
  id: '/returns/monthly/new',
  path: '/returns/monthly/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsMonthlyIdRoute = ReturnsMonthlyIdRouteImport.update({
  id: '/returns/monthly/$id',
  path: '/returns/monthly/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsDailyNewRoute = ReturnsDailyNewRouteImport.update({
  id: '/returns/daily/new',
  path: '/returns/daily/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsDailyIdRoute = ReturnsDailyIdRouteImport.update({
  id: '/returns/daily/$id',
  path: '/returns/daily/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerCaseIdRoute = OfficerCaseIdRouteImport.update({
  id: '/officer/case/$id',
  path: '/officer/case/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/obligations': typeof ObligationsRoute
  '/officer/history': typeof OfficerHistoryRoute
  '/officer/queue': typeof OfficerQueueRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/returns/new': typeof ReturnsNewRoute
  '/system/outbox': typeof SystemOutboxRoute
  '/system/validation': typeof SystemValidationRoute
  '/officer/': typeof OfficerIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/system/': typeof SystemIndexRoute
  '/officer/case/$id': typeof OfficerCaseIdRoute
  '/returns/daily/$id': typeof ReturnsDailyIdRoute
  '/returns/daily/new': typeof ReturnsDailyNewRoute
  '/returns/monthly/$id': typeof ReturnsMonthlyIdRoute
  '/returns/monthly/new': typeof ReturnsMonthlyNewRoute
  '/returns/daily/': typeof ReturnsDailyIndexRoute
  '/returns/monthly/': typeof ReturnsMonthlyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/obligations': typeof ObligationsRoute
  '/officer/history': typeof OfficerHistoryRoute
  '/officer/queue': typeof OfficerQueueRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/returns/new': typeof ReturnsNewRoute
  '/system/outbox': typeof SystemOutboxRoute
  '/system/validation': typeof SystemValidationRoute
  '/officer': typeof OfficerIndexRoute
  '/returns': typeof ReturnsIndexRoute
  '/system': typeof SystemIndexRoute
  '/officer/case/$id': typeof OfficerCaseIdRoute
  '/returns/daily/$id': typeof ReturnsDailyIdRoute
  '/returns/daily/new': typeof ReturnsDailyNewRoute
  '/returns/monthly/$id': typeof ReturnsMonthlyIdRoute
  '/returns/monthly/new': typeof ReturnsMonthlyNewRoute
  '/returns/daily': typeof ReturnsDailyIndexRoute
  '/returns/monthly': typeof ReturnsMonthlyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/obligations': typeof ObligationsRoute
  '/officer/history': typeof OfficerHistoryRoute
  '/officer/queue': typeof OfficerQueueRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/returns/new': typeof ReturnsNewRoute
  '/system/outbox': typeof SystemOutboxRoute
  '/system/validation': typeof SystemValidationRoute
  '/officer/': typeof OfficerIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/system/': typeof SystemIndexRoute
  '/officer/case/$id': typeof OfficerCaseIdRoute
  '/returns/daily/$id': typeof ReturnsDailyIdRoute
  '/returns/daily/new': typeof ReturnsDailyNewRoute
  '/returns/monthly/$id': typeof ReturnsMonthlyIdRoute
  '/returns/monthly/new': typeof ReturnsMonthlyNewRoute
  '/returns/daily/': typeof ReturnsDailyIndexRoute
  '/returns/monthly/': typeof ReturnsMonthlyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/obligations'
    | '/officer/history'
    | '/officer/queue'
    | '/returns/$id'
    | '/returns/new'
    | '/system/outbox'
    | '/system/validation'
    | '/officer/'
    | '/returns/'
    | '/system/'
    | '/officer/case/$id'
    | '/returns/daily/$id'
    | '/returns/daily/new'
    | '/returns/monthly/$id'
    | '/returns/monthly/new'
    | '/returns/daily/'
    | '/returns/monthly/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/obligations'
    | '/officer/history'
    | '/officer/queue'
    | '/returns/$id'
    | '/returns/new'
    | '/system/outbox'
    | '/system/validation'
    | '/officer'
    | '/returns'
    | '/system'
    | '/officer/case/$id'
    | '/returns/daily/$id'
    | '/returns/daily/new'
    | '/returns/monthly/$id'
    | '/returns/monthly/new'
    | '/returns/daily'
    | '/returns/monthly'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/login'
    | '/obligations'
    | '/officer/history'
    | '/officer/queue'
    | '/returns/$id'
    | '/returns/new'
    | '/system/outbox'
    | '/system/validation'
    | '/officer/'
    | '/returns/'
    | '/system/'
    | '/officer/case/$id'
    | '/returns/daily/$id'
    | '/returns/daily/new'
    | '/returns/monthly/$id'
    | '/returns/monthly/new'
    | '/returns/daily/'
    | '/returns/monthly/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LoginRoute: typeof LoginRoute
  ObligationsRoute: typeof ObligationsRoute
  OfficerHistoryRoute: typeof OfficerHistoryRoute
  OfficerQueueRoute: typeof OfficerQueueRoute
  ReturnsIdRoute: typeof ReturnsIdRoute
  ReturnsNewRoute: typeof ReturnsNewRoute
  SystemOutboxRoute: typeof SystemOutboxRoute
  SystemValidationRoute: typeof SystemValidationRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  ReturnsIndexRoute: typeof ReturnsIndexRoute
  SystemIndexRoute: typeof SystemIndexRoute
  OfficerCaseIdRoute: typeof OfficerCaseIdRoute
  ReturnsDailyIdRoute: typeof ReturnsDailyIdRoute
  ReturnsDailyNewRoute: typeof ReturnsDailyNewRoute
  ReturnsMonthlyIdRoute: typeof ReturnsMonthlyIdRoute
  ReturnsMonthlyNewRoute: typeof ReturnsMonthlyNewRoute
  ReturnsDailyIndexRoute: typeof ReturnsDailyIndexRoute
  ReturnsMonthlyIndexRoute: typeof ReturnsMonthlyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obligations': {
      id: '/obligations'
      path: '/obligations'
      fullPath: '/obligations'
      preLoaderRoute: typeof ObligationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/': {
      id: '/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof ReturnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/validation': {
      id: '/system/validation'
      path: '/system/validation'
      fullPath: '/system/validation'
      preLoaderRoute: typeof SystemValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/outbox': {
      id: '/system/outbox'
      path: '/system/outbox'
      fullPath: '/system/outbox'
      preLoaderRoute: typeof SystemOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/new': {
      id: '/returns/new'
      path: '/returns/new'
      fullPath: '/returns/new'
      preLoaderRoute: typeof ReturnsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/$id': {
      id: '/returns/$id'
      path: '/returns/$id'
      fullPath: '/returns/$id'
      preLoaderRoute: typeof ReturnsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/queue': {
      id: '/officer/queue'
      path: '/officer/queue'
      fullPath: '/officer/queue'
      preLoaderRoute: typeof OfficerQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/history': {
      id: '/officer/history'
      path: '/officer/history'
      fullPath: '/officer/history'
      preLoaderRoute: typeof OfficerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/monthly/': {
      id: '/returns/monthly/'
      path: '/returns/monthly'
      fullPath: '/returns/monthly/'
      preLoaderRoute: typeof ReturnsMonthlyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/daily/': {
      id: '/returns/daily/'
      path: '/returns/daily'
      fullPath: '/returns/daily/'
      preLoaderRoute: typeof ReturnsDailyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/monthly/new': {
      id: '/returns/monthly/new'
      path: '/returns/monthly/new'
      fullPath: '/returns/monthly/new'
      preLoaderRoute: typeof ReturnsMonthlyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/monthly/$id': {
      id: '/returns/monthly/$id'
      path: '/returns/monthly/$id'
      fullPath: '/returns/monthly/$id'
      preLoaderRoute: typeof ReturnsMonthlyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/daily/new': {
      id: '/returns/daily/new'
      path: '/returns/daily/new'
      fullPath: '/returns/daily/new'
      preLoaderRoute: typeof ReturnsDailyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/daily/$id': {
      id: '/returns/daily/$id'
      path: '/returns/daily/$id'
      fullPath: '/returns/daily/$id'
      preLoaderRoute: typeof ReturnsDailyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/case/$id': {
      id: '/officer/case/$id'
      path: '/officer/case/$id'
      fullPath: '/officer/case/$id'
      preLoaderRoute: typeof OfficerCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LoginRoute: LoginRoute,
  ObligationsRoute: ObligationsRoute,
  OfficerHistoryRoute: OfficerHistoryRoute,
  OfficerQueueRoute: OfficerQueueRoute,
  ReturnsIdRoute: ReturnsIdRoute,
  ReturnsNewRoute: ReturnsNewRoute,
  SystemOutboxRoute: SystemOutboxRoute,
  SystemValidationRoute: SystemValidationRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  ReturnsIndexRoute: ReturnsIndexRoute,
  SystemIndexRoute: SystemIndexRoute,
  OfficerCaseIdRoute: OfficerCaseIdRoute,
  ReturnsDailyIdRoute: ReturnsDailyIdRoute,
  ReturnsDailyNewRoute: ReturnsDailyNewRoute,
  ReturnsMonthlyIdRoute: ReturnsMonthlyIdRoute,
  ReturnsMonthlyNewRoute: ReturnsMonthlyNewRoute,
  ReturnsDailyIndexRoute: ReturnsDailyIndexRoute,
  ReturnsMonthlyIndexRoute: ReturnsMonthlyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
